name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.2.0' # You can specify the Flutter version here

      # Install dependencies using flutter pub
      - name: Install dependencies
        run: flutter pub get

      # Analyze project source
      - name: Analyze project source
        run: flutter analyze
